# Generated by Django 5.0.6 on 2024-05-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyreg',
            name='B_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babyreg',
            name='fathers_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babyreg',
            name='mothers_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
