# Generated by Django 4.2.13 on 2024-05-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0002_alter_babyreg_b_number_alter_babyreg_fathers_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('half_day', 'Half Day Payment (10,000 UGX)'), ('full_day', 'Full Day Payment (15,000 UGX)')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('babies_assigned', models.IntegerField(default=0)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('S_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DaystarApp.sitter')),
            ],
        ),
    ]
