# Generated by Django 4.2.13 on 2024-05-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=100),
        ),
    ]
