# Generated by Django 4.2.13 on 2024-05-18 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0005_alter_babyreg_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doll_number', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('c_doll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DaystarApp.category_doll')),
            ],
        ),
    ]
