# Generated by Django 4.2.13 on 2024-05-18 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0006_category_doll_doll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyattendance',
            name='timeOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Salesrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(default=0)),
                ('amount_received', models.IntegerField(default=0)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('unit_price', models.IntegerField(default=0)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DaystarApp.doll')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DaystarApp.babyreg')),
            ],
        ),
    ]
