# Generated by Django 4.2.13 on 2024-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0007_alter_babyattendance_timeout_salesrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterattendance',
            name='timeIn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sitterattendance',
            name='timeOut',
            field=models.DateTimeField(),
        ),
    ]
