# Generated by Django 4.2.13 on 2024-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0008_alter_sitterattendance_timein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
