# Generated by Django 4.2.13 on 2024-05-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0009_alter_sitter_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doll',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sale_date',
            field=models.DateTimeField(),
        ),
    ]
