# Generated by Django 4.2.13 on 2024-05-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0012_sitterattendance_assign_baby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterattendance',
            name='timeIn',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sitterattendance',
            name='timeOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
